apiVersion: apps/v1
kind: Deployment
metadata:
  name: reg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reg
  template:
    metadata:
      labels:
        app: reg
    spec:
      containers:
      - image: okteto.dev/reg:latest
        name: reg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "6aff04a5-b907-43ab-97f2-cd036ebfb299"
        - name: Vless_Path
          value: "/vlfg555"
        - name: Vmess_UUID
          value: "6aff04a5-b907-43ab-97f2-cd036ebfb299"
        - name: Vmess_Path
          value: "/vm6fnnnf66"
        - name: Share_Path
          value: "/v2link"
